### ISSUE TITLE
[suyong] stack_queue

### ISSUE THREAD

**Issue by maplesuyong** [2022-PACOS/python-codingtest-study#18]
[[Baekjoon-1406] 에디터]

[[Baekjoon-13335] 트럭]

[[Baekjoon-2800] 괄호 제거]

[[Baekjoon-3078] 좋은 친구]

죄송합니다..

**Comment by aaajeong** [comment]
1. 에디터
수용님도 처음에 cursor를 따로 만들고 조건에 맞게 수행하셨네요!
저도 완전히 똑같진 않지만 동일한 접근으로 구현했다가 시간초과 얻었습니다..ㅎ
구현이 너무 쉽다했는데 역시나 입력값의 크기가 크더군요..!
리스트에서 insert, delete, remove의 시간복잡도는 O(N)이라는 것을 참고하면 좋을 것 같습니다. (저도 복습했네요.)

2. 좋은친구
수용님이 참고한 모범답안도 제가 참고한 코드와 살짝 다르네요!
어려운 문제이니 손으로 그려보면서 잘 이해해보겠습니다 :)
